/*
------------------------------------------------------------------

 						        AULA 9 (17/02/25)
                                TEMA: PROCEDURES
						       THIAGO OLSZEWSKI

------------------------------------------------------------------
*/

CREATE OR REPLACE PROCEDURE INSERIR_PARTIDA(ID INTEGER, TIME_1 INTEGER, TIME_2 INTEGER, 
    TIME_1_GOLS INTEGER, TIME_2_GOLS INTEGER) AS $$

BEGIN
    INSERT INTO PARTIDA(ID, TIMES_1, TIMES_2, TIMES_1_GOLS, TIMES_2_GOLS)
    VALUES (ID, TIME_1, TIME_2, TIME_1_GOLS, TIME_2_GOLS);
END;
$$ LANGUAGE plpgsql;

CALL INSERIR_PARTIDA(10, 5, 1, 2, 3);

-- UPDATE NOME DO TIME
CREATE OR REPLACE PROCEDURE ALTERA_NOME_TIME(ID_TIME INTEGER, NOVO_NOME VARCHAR(50)) AS $$
BEGIN
    UPDATE AU8.TIMES SET NOME = NOVO_NOME WHERE ID = ID_TIME;
    IF NOT FOUND ID THEN
        RAISE EXCEPTION 'TIME DE ID % NÃO ENCONTRADO', ID_TIME;
    END IF;
END
$$ LANGUAGE plpgsql;

CALL ALTERA_NOME_TIME(1, 'Flamengo');

-- PROCEDURE DE EXCLUIR PARTIDA COM EXCEÇÃO
CREATE OR REPLACE PROCEDURE EXCLUIR_PARTIDA(ID_PARTIDA INTEGER) AS $$
BEGIN
    DELETE FROM AU8.PARTIDA WHERE ID = ID_PARTIDA;
    IF NOT FOUND ID THEN
        RAISE EXCEPTION 'PARTIDA DE ID % NÃO ENCONTRADA', ID_PARTIDA;
    ELSE
        RAISE NOTICE 'PARTIDA DE ID % EXCLUÍDA COM SUCESSO!', ID_PARTIDA;
    END IF;
END;
$$ LANGUAGE plpgsql;

CALL EXCLUIR_PARTIDA(8);