/*
------------------------------------------------------------------

 						AULA 3 (03/02/25)
						THIAGO OLSZEWSKI

------------------------------------------------------------------
*/


-- SELECIONAR O CPF DE TODOS OS EMPREGADOS QUE TRABALHAM
-- NO MESMO PROJETO E COM A MEMSA QUANTIDADE DE HORAS
-- QUE O EMPREGADO CUJO CPF É 33333333333, OLHANDO A TABELA
-- EMPREGADO, TRABALHA_EM E PROJETO


SELECT DISTINCT FK_CPFE 
FROM TESTES.TRABALHA_EM 
WHERE (FK_NUMPROJ, HORAS) IN (
    SELECT FK_NUMPROJ, HORAS 
    FROM TESTES.TRABALHA_EM 
    WHERE FK_CPFE = '33333333333'
);

SELECT DISTINCT T1.FK_CPFE
FROM TESTES.TRABALHA_EM T1
JOIN TESTES.TRABALHA_EM T2
ON T1.FK_NUMPROJ = T2.FK_NUMPROJ AND T1.HORAS = T2.HORAS
WHERE T2.FK_CPFE = '33333333333'

-- SELECIONE O NOME DE TODOS OS EMPREGADOS COM SALÁRIO MAIOR
-- DO QUE TODOS OS SALÁRIOS DOS EMPREGADOS DO DEPARTAMENTO 1
SELECT DISTINCT E.NOME FROM TESTES.EMPREGADO E
WHERE E.SALARIO > 
( SELECT E.SALARIO FROM TESTES.EMPREGADO E
WHERE E.FK_NUMDPT = 1 )
ORDER BY E.NOME ASC;