SHOW DATABASES;
USE DIGIX;
CREATE TABLE IF NOT EXISTS USER (
    ID  INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
    NAME  VARCHAR(255) NOT NULL ,
    EMAIL  VARCHAR(255) NOT NULL ,
    PASSWORD  VARCHAR(255) NOT NULL ,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO USER (NAME, EMAIL, PASSWORD) VALUES ('John Doe', 'john.doe@example.com', 'Root1234');

SELECT * FROM USER;

UPDATE USER SET NAME = 'THIAGO' WHERE ID = 1;