/*
------------------------------------------------------------------

 						AULA 1 (27/01/25)
						THIAGO OLSZEWSKI

------------------------------------------------------------------
*/


-- DDL

-- CRIAR TABELA
CREATE TABLE USUARIO (
	ID INTEGER NOT NULL PRIMARY KEY,
	NOME	VARCHAR(40),
	EMAIL	VARCHAR(40)
);

-- USANDO FOREIGN KEY
CREATE TABLE CARGO (
	ID	INTEGER NOT NULL PRIMARY KEY,
	NOME	VARCHAR(30),
	USUARIO	INTEGER,
	CONSTRAINT FK_CARGO_USUARIO FOREIGN KEY(USUARIO)
	REFERENCES USUARIO(ID)
);

-- ALTERAR TABELA
-- ADICIONAR COLUNA
ALTER TABLE CARGO ADD COLUMN SALARIO DECIMAL(10, 2);
-- ALTERAR TIPO DE COLUNA
ALTER TABLE CARGO ALTER COLUMN NOME TYPE VARCHAR(60);
-- APAGAR COLUNA
ALTER TABLE CARGO DROP COLUMN SALARIO;

-- EXCLUIR TABELA
DROP TABLE CARGO;
DROP TABLE USUARIO;

---------------------------------------------------------------------

-- DML

-- ADICIONAR VALORES NAS TABELAS
INSERT INTO USUARIO VALUES (1, 'THIAGO OLSZEWSKI DE CARVALHO', 'thiago.olszewskioc@gmail.com');
INSERT INTO USUARIO VALUES (2, 'RONALDO TAVEIRA', 'ronaldotav@gmail.com');
INSERT INTO USUARIO VALUES (3, 'MARIA ROBERTA', 'mariro@gmail.com');

-- CARDINALIDADE 1 -> N, POIS UM USUARIO PODE TER VÁRIOS CARGOS
INSERT INTO CARGO VALUES (1, 'ANALISTA', 1, 5000.00);
INSERT INTO CARGO VALUES (2, 'GERENTE', 1, 5000.00);
INSERT INTO CARGO VALUES (3, 'PRODUCT OWNER', 2, 5000.00);

-- ALTERAR VALORES (PODE SER SEPARADO EM LINHAS)
UPDATE CARGO SET SALARIO = 8000.00 WHERE ID = 2;

-- SELECIONAR VALORES DAS TABELAS
SELECT * FROM CARGO;
SELECT * FROM USUARIO;
-- SELECT COLUNAS(* = TODAS) FROM TABELA WHERE CONDIÇÃO
SELECT NOME, SALARIO FROM CARGO WHERE SALARIO >= 6000.00;

-- DELETAR REGISTROS (SEMPRE COM WHERE)
DELETE FROM USUARIO WHERE ID = 3;

-- LEFT JOIN (INTERSECÇÃO) - RETORNA TODAS OS USUÁRIOS E SEUS CARGOS
SELECT * FROM USUARIO LEFT JOIN CARGO ON USUARIO.ID = CARGO.USUARIO;

-- RIGHT JOIN (INTERSECÇÃO) - RETORNA TODOS OS CARGOS E SEUS USUÁRIOS
SELECT * FROM USUARIO RIGHT JOIN CARGO ON USUARIO.ID = CARGO.USUARIO